<<<<<<< HEAD
# Generated by Django 3.0.8 on 2021-12-11 00:39
=======
# Generated by Django 3.0.8 on 2021-12-14 18:46
>>>>>>> 19fa1a16481a84c18068bbf1e742116eaec4bc77

import apps.posts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
=======
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post/', validators=[apps.posts.models.validar_extension])),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Categoria')),
                ('dislike', models.ManyToManyField(related_name='dislikesPost', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='likesPost', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 19fa1a16481a84c18068bbf1e742116eaec4bc77
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post/', validators=[apps.posts.models.validar_extension])),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Categoria')),
=======
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsPost', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 19fa1a16481a84c18068bbf1e742116eaec4bc77
            ],
        ),
    ]
